### ISSUE TITLE
ArcGISARView performance problems

### ISSUE THREAD

**Issue by ech-algr** [Esri/arcgis-runtime-toolkit-ios#100]
ArcGISARView frame rate drops when device pitch is changed (horizontal) - blocking sceneView.renderFrame() call takes more than 1 second

**Comment by mhdostal** [comment]
@ech-algr Can you give some more information on the type of device you're using, iOS version, what kind of layers are in your `AGSScene`, what version of Xcode you're using, etc.?  This will help diagnose the problem and address any potential issues.  Thank you for your feedback!

**Comment by ech-algr** [comment]
Devices are iPhone XR, 11, 7,... iOS 13.3, xCode 11.3.1 
Tried this with different scenes - in simplest case AGSScene has imagery basemap and one small 2D Feature layer. After a while sometimes app crashes. Complex scenes are slower.
 
Probably you can reproduce this problem with modified code from Toolkit Examples:
    private func imageryScene() -> AGSScene {
        
        // MARK: - camera and service parameters
        let cameraElevation = 10.0
        let cameraViewpoint = AGSPoint( x: -117.195777, y: 34.056237, spatialReference: AGSSpatialReference.wgs84())
        let featureServiceUrl = "https://sampleserver6.arcgisonline.com/arcgis/rest/services/Energy/HSEC/FeatureServer/0"
        let clippingDistance = 750.0
        
        
        // Create scene with the streets basemap.
        let scene = AGSScene(basemapType: .imageryWithLabels)
        scene.addElevationSource()
        
        let testTable = AGSServiceFeatureTable(url: URL(string: featureServiceUrl)!)
        let featurelayer = AGSFeatureLayer(featureTable: testTable)
        scene.operationalLayers.add(featurelayer)
        
        scene.load { [weak self, weak scene] (error) in
             self?.statusViewController?.errorMessage = error?.localizedDescription
             if error != nil {
                 return
             }
             scene?.baseSurface?.elevationSources.first?.load { (error) in
                 self?.statusViewController?.errorMessage = error?.localizedDescription
                 if error != nil {
                     return
                 }
                 
                 // Find the elevation of the layer at the camera point.
                 scene?.baseSurface?.elevation(for: cameraViewpoint) { (elevation, error) in
                     self?.statusViewController?.errorMessage = error?.localizedDescription
                     if error != nil {
                         return
                     }
                     
                     // Create the origin camera at the camera point and elevation of the data.
                     let camera = AGSCamera(latitude: cameraViewpoint.y, longitude: cameraViewpoint.x, altitude: elevation + cameraElevation, heading: 0, pitch: 90, roll: 0)
                     self?.arView.originCamera = camera
                     self?.arView.translationFactor = 1
                     
                     // Set the clipping distance 
                     self?.arView.clippingDistance = clippingDistance
                 }
             }
        }

        arView.locationDataSource = nil
        arView.translationFactor = 1
        return scene
    }

**Comment by mhdostal** [comment]
@ech-algr - Thank you for the code, with it I was able to reproduce your issue.  The frame rate slowdown is due to the combination of `translationFactor` and `clippingDistance`, specifically, using `translationFactor = 1` and the `clippingDistance` of `750`.

What type of AR experience are you creating?  We have a guide-doc [here](https://developers.arcgis.com/ios/latest/swift/guide/display-scenes-in-augmented-reality.htm) that describes the various types and recommended settings for the various properties.  Setting the `translationFactor = 1` is appropriate for a world-scale experience, but setting the `clippingDistance = 750` is typical for table-top or flyover scenarios.

In your code, setting the `clippingDistance` to `0` will disable clipping distance and prevent the frame-rate issue you were seeing.  Likewise, setting the `translationFactor` to `1000` will also resolve the frame-rate issue.  I suggest playing around with those values to find something that gives you the experience you desire along with a good frame-rate.

I will see what we can do in the Runtime SDK to improve the frame-rate for this combination of properties, so I'll leave this open for a bit.

If you have any more questions or comments, please let me know.

**Comment by ech-algr** [comment]
@mhdostal - Thank you - clippingDistance = 0 solved this problem for now. I am creating world-scale experience - only translationFactor = 1 is an option.
