### ISSUE TITLE
Please help me on how to use Cluster feature  in ARCGIS map for iOS Application 

### ISSUE THREAD

**Issue by nafeesahmedrao** [Esri/arcgis-runtime-toolkit-ios#54]
I want to integrate cluster feature in my iOS app, please help me on this.

**Comment by nixta** [comment]
Could you tell us more about your specific requirements and the project you intend to use this on?

There is a plugin built for the previous version of the Runtime (10.2.x) [here](https://github.com/nixta/clusterlayer-plugin-ios), but it has not yet been re-engineered for Runtime 100.x.

**Comment by nafeesahmedrao** [comment]
Hello,

The plugin you referred is for objective c code, could you please elaborate
on this  how to use in swift 4.2 and xcode 10.2
My requirements are almost same as it is in this plugin.

Thank You
Nafees Ahmad
iOS  Developer
+971 505965715

**Comment by nixta** [comment]
The Objective-C isn't really the problem (you'd just [configure your project with a bridging header](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)).

The real problem is that the plugin doesn't work with the current Runtime. Please keep an eye on [this issue](https://github.com/nixta/clusterlayer-plugin-ios/issues/22) for updates on that.

**Comment by nafeesahmedrao** [comment]
You mean I should take  pod 'ArcGIS-Runtime-SDK-iOS', '100.0' for cluster compatibility.

**Comment by nixta** [comment]
No. I’m sorry. I’m confusing things for you.

There is currently no clustering support for Runtime SDK.

The repo I linked to was compatible with the **old** Runtime SDK. I only mentioned it in case you wanted to build your own solution based off it but it will not work for you as is.

**Comment by nixta** [comment]
Closing this issue. If interested, monitor https://github.com/nixta/clusterlayer-plugin-ios/issues/22 instead.
