### ISSUE TITLE
AR not working on iOS 12 devices

### ISSUE THREAD

**Issue by armandzwan** [Esri/arcgis-runtime-toolkit-ios#99]
When running the demo app on iOS 12 devices, the AR sample is not showing the camera feed.
It does work on iOS 13 devices.

How can I get them to work?

**Comment by mhdostal** [comment]
Armand, can you supply some more information about which version of iOS 12 you are running and on what devices?  When you run on a device, are you seeing any information in the Xcode console that gives you a clue as to what the problem is?

This is unlikely, but has the app been granted permission to use the camera?  You can either uninstall and reinstall the app to get the request for access again or give access to the app in the Settings.

**Comment by armandzwan** [comment]
Never mind. It was because these devices do not have at least an A9 processor (mini 2, Air 2), thus ARKit is not available. Maybe a popup stating this would help for developers starting with these examples?

**Comment by mhdostal** [comment]
@armandzwan Ok, thank you for the update and your feedback!
